### ISSUE TITLE
ISSUE: Decompiler not retaining directory structure

### ISSUE THREAD

**Issue by Mookins** [sotasan/decompiler#8]
The decompiler isn't keeping nested files in place, Instead its just piling them all under the top directory.

This makes it incredibly annoying to track down when you have 500 a.class files together randomly not where they are supposed to be
![Screenshot 2024-04-01 at 1 24 55 PM](https://github.com/sotasan/decompiler/assets/131602358/7d69e73c-1540-4a31-a605-866c3b0fb692)
.

**Comment by sotasan** [comment]
It looks like the jar was obfuscated, maybe the obfuscator moved it into the root directory. Can you please verify that with an archiver?

**Comment by Mookins** [comment]
Nope its fine when opened in other decompilers or unzipped, its not just this one I have seen it before I have moved to another tool now.

**Comment by sotasan** [comment]
Unfortunately it‘s quite hard to pin down the issue this way, is there any way you could provide me with a minimal example jar where this behavior occurs?

Were the other jars, where you have experienced this issue, obfuscated as well?

**Comment by sotasan** [comment]
Stale issue
